Traceback (most recent call last):
  File "/home/ludch/miniconda3/envs/jupyter_book/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ludch/miniconda3/envs/jupyter_book/lib/python3.10/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ludch/miniconda3/envs/jupyter_book/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ludch/miniconda3/envs/jupyter_book/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/ludch/miniconda3/envs/jupyter_book/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/ludch/miniconda3/envs/jupyter_book/lib/python3.10/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/home/ludch/miniconda3/envs/jupyter_book/lib/python3.10/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/ludch/miniconda3/envs/jupyter_book/lib/python3.10/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import tensorflow as tf
import pkg_resources

for i, gpu in enumerate(tf.config.list_physical_devices('GPU')):
    print('Gpu %d:' % i, gpu)
print()

tf.config.experimental.set_memory_growth(tf.config.list_physical_devices('GPU')[0], True)

# Set mixed precision
if pkg_resources.parse_version(tf.__version__)  < pkg_resources.parse_version("2.4.0"):
    tf.keras.mixed_precision.experimental.set_policy("mixed_float16")
    print("Mixed precision policy:", tf.keras.mixed_precision.experimental.global_policy())
else:
    tf.keras.mixed_precision.set_global_policy("mixed_float16")
    print("Mixed precision policy:", tf.keras.mixed_precision.global_policy())
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [6][0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mtensorflow[39;00m [38;5;28;01mas[39;00m [38;5;21;01mtf[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mpkg_resources[39;00m
[1;32m      4[0m [38;5;28;01mfor[39;00m i, gpu [38;5;129;01min[39;00m [38;5;28menumerate[39m(tf[38;5;241m.[39mconfig[38;5;241m.[39mlist_physical_devices([38;5;124m'[39m[38;5;124mGPU[39m[38;5;124m'[39m)):

[0;31mModuleNotFoundError[0m: No module named 'tensorflow'
ModuleNotFoundError: No module named 'tensorflow'

